services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      spring.datasource.url: jdbc:mysql://host.docker.internal:3306/cafe
    ports:
      - "3202:8080"
    restart: always

#  db:
#    image: postgres
#    environment:
#      POSTGRES_PASSWORD: 123
#      POSTGRES_USER: postgres
#      POSTGRES_DB: cafe
#    ports:
#      - "5432:5432"
  frontend:
    build:
      context: C:\Users\nouri\cafe-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - app
    restart: always