spring.application.name=cafe
spring.datasource.url=jdbc:mysql://localhost:3306/cafe
spring.datasource.username=root
spring.datasource.password=22733242Na
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true






management.endpoints.web.exposure.include="*"
management.info.env.enabled=true

info.app.name=Uncle Bob cafe
info.app.description=tea
info.app.version=1.0.0